Clear screenshots task
avito-tech/avito-android pull request #103
Opened 2020-01-27 09:04 UTC by DEADMC

Таска для очистки скриншотов на девайсе. Исполняться будет исключительно локально перед запуском тестов для пуллинга скриншотов

2020-01-27 13:18 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +        val applicationId = variant?.testVariant?.applicationId ?: return
абстракция протекает, ставь параметром сразу applicationID

2020-01-27 13:19 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +    @Internal
почему Internal? это самый что ни на есть Input, смена значения должна инвалидировать output

2020-01-27 13:26 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +        val currentDevice = getCurrentDevice(ciLogger) ?: return
не знаю как ты, но эти return после ?: вообще не видны в коде, очень долго уходить на понимание что отсюда можем выйти.

мб лучше в явные if класть?

2020-01-27 13:28 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +                file.delete()
надо обработать эксепшены и вывести, решить падать ли сразу или пытаться почистить что получается

2020-01-27 13:29 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +                throw exception
точно хочешь чтобы этой таской нельзя было управлять и падать несмотря на suppressFailures?

2020-01-27 13:31 UTC, dsvoronin requested changes
В документации нужно как-то отразить?

2020-01-27 14:43 UTC, dsvoronin requested changes

2020-01-27 14:43 UTC, dsvoronin commented on gradle.properties
> +projectVersion=2020.1.29
апни версию, 29 уже вмерджили

2020-01-27 14:46 UTC, eugene-krivobokov commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +    @Internal
input/output используются не только для кеширования, но и для определения up-to-date

2020-01-27 14:48 UTC, eugene-krivobokov commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +        val currentDevice = getCurrentDevice(ciLogger) ?: return
меня больше путает не синтаксис, а то что молча выходим
это может привести к долгому дебагу проблемы, когда все отработало, а результата нет

2020-01-27 15:51 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +    @Internal
да, я для упрощения считаю это все неким `avoidance`

2020-01-27 16:25 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +        val applicationId = variant?.testVariant?.applicationId ?: return
просто applicationID - unresolved reference

2020-01-27 16:27 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +        val applicationId = variant?.testVariant?.applicationId ?: return
done

2020-01-27 16:27 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +    @Internal
done

2020-01-27 16:31 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +        val currentDevice = getCurrentDevice(ciLogger) ?: return
Про долгий дебаг справедливо, допилил

2020-01-27 16:35 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +                file.delete()
done

2020-01-27 16:37 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +                throw exception
done

2020-01-27 16:44 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +    @Input
ошибка, cilogger как раз никогда не должен быть input

2020-01-27 16:45 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +        if (applicationId == null) {
а разве он может быть null?

2020-01-27 16:46 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +                throw exception
ты сделал не nullable но таска очистки будет ронять билд
это плохо

2020-01-27 18:50 UTC, eugene-krivobokov commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
не понял зачем вынесли в utils
судя по названию класса AdbDeviceResolver, ожидал что это и будет его ответственность - найти и вернуть девайс

2020-01-27 18:53 UTC, eugene-krivobokov approved these changes

2020-01-27 18:55 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
ну кстати да, вынес просто до того как создал AdbDeviceResolver

2020-01-27 19:00 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +    @Input
поправил

2020-01-27 19:00 UTC, DEADMC commented on gradle.properties
> +projectVersion=2020.1.29
fixed

2020-01-27 19:05 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
> +        if (applicationId == null) {
нет, убрал

2020-01-27 19:10 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
С другой стороны совмещать их в одном файле тоже такое себе, так как тогда не поменять реализацию чего-то одного. Самый правильный и гибкий вариант это 2 SAM интерфейса для getDevice и resolve, но тогда кажется это совсем оверхед.

2020-01-27 19:10 UTC, dsvoronin requested changes

2020-01-27 19:10 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/AdbDeviceResolver.kt
> +    fun resolve(eitherDevice: Either<AdbDevice, Exception>): AdbDevice
в неявном контракте другой порядок:
Either<Exception, Value> 
это из доке про Either

2020-01-27 19:10 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ScreenshotsPlugin.kt
> -                    variant = applicationVariant
а кто за тебя вариант проставит?)
variant.set(applicationVariant)

2020-01-27 19:10 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ScreenshotsPlugin.kt
> +                    description = "Clear screenshots on device"
и тут тоже надо проставить вариант

2020-01-27 19:10 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
их важно разделять, Resolver - название непонятное, суть такая:

есть функция которая достает девайс - она должна достать девайс или сказать что этого сделать не выйдет по такой-то причине

решать что делать с информацией что "не вышло" должна уже другая сущность, т.к. это приведет к падению билда или просто к ошибке в лог, это должно управляться снаружи, грейдловая сущность, пересекать их снова -не нужно

2020-01-27 19:15 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/ScreenshotsPlugin.kt
> -                    variant = applicationVariant
думал раз там присвоили то хватит xD

2020-01-27 19:21 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/ScreenshotsPlugin.kt
> -                    variant = applicationVariant
там ты создал проперти пустой

2020-01-27 19:26 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
ну вот теперь вроде норм, разделено)

2020-01-27 19:42 UTC, eugene-krivobokov commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
> С другой стороны совмещать их в одном файле тоже такое себе

Кажется, что изначально разделили на две сущности и исходим из того, что так и должно быть.
Для меня это выглядит как одна ответственность - найти девайс.
Выделять обработку ошибки в отдельную абстракцию выглядит как преждевременная абстракция.
Есть интерфейс Resolver, у него реализация - Local...
Когда будет другая реализация Resolver, то в ней возможно другая обработка понадобится. Мы этого еще не знаем.

2020-01-27 19:45 UTC, eugene-krivobokov commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
Дополнительный маркер для меня - это получившееся название - "Handler".
Это примерно как "Processor" - что-то делает, что-то обрабатывает, но что именно - хз.

Если трудно подобрать осмысленное название абстракции, то возможно она ничего полезного и не делает, не нужна.

2020-01-27 19:47 UTC, eugene-krivobokov commented
> В документации нужно как-то отразить?

Сломал обновление документации. Как починю, залью.

2020-01-27 19:54 UTC, eugene-krivobokov commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
Согласен, что "resolver" не должен сам решать что нужно падать. Просто пока не вижу пользы в отдельной абстракции для этого решения. 
Здесь же нет какой-то хитрой стратегии, которую нужно переиспользовать. Все просто - или идем дальше, или падаем. Считаю что для таких простых решений отдельные абстракции больше вредят, усложняют код.

2020-01-28 07:59 UTC, DEADMC commented on design-screenshots/src/main/kotlin/com/avito/plugin/AdbDeviceResolver.kt
> +    fun resolve(eitherDevice: Either<AdbDevice, Exception>): AdbDevice
done

2020-01-28 09:33 UTC, dsvoronin commented on design-screenshots/src/main/kotlin/com/avito/plugin/LocalAdbUtil.kt
> +internal fun getDevice(adbDevicesManager: DevicesManager, adbDeviceResolver: AdbDeviceResolver): AdbDevice {
Все в порядке, у нас уже в нескольких местах требуется один девайс
`adbDevicesManager.connectedDevices()` - предоставляет все
можно к нему же в пакет положить .single() extension, который вернет Either

Handler / Resolver - это трэш, да, сразу показывает что не понятно для чего класс делаешь
а понятно станет когда suppressFailures контракт сверху прилетит, а понадобиться это на следующем шаге, я просто предложил Андрею сразу заложиться

2020-01-28 09:33 UTC, dsvoronin approved these changes

2020-01-28 09:34 UTC, dsvoronin approved these changes

2020-01-28 09:36 UTC, merged