Remove deployments when they are not needed
avito-tech/avito-android pull request #1323
Opened 2022-02-01 18:44 UTC by materkey

Example:
1st deployment is [redroid](https://github.com/remote-android/redroid-doc)
2nd deployment is QEMU emulators for GPS, camera, google services, etc.

Expected:
When tests for one of the deployments finished I want the deployment to be destroyed 

Actual:
They are idling until end

2022-02-08 13:16 UTC, sboishtyan requested changes

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/client/src/main/kotlin/com/avito/runner/scheduler/runner/TestRunnerImpl.kt
> +                                state.deviceSignals.send(Device.Signal.ReservationNotNeeded(deviceName))
That is not a DeviceSignal. We should use new channel. For example testRunSignals. And create TestRequestsForDeviceIsOver(deviceName: DeviceName)

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/client/src/main/kotlin/com/avito/runner/scheduler/runner/TestRunnerImpl.kt
> +                        gottenResultsByDeviceName[result.request.testCase.deviceName.name]?.add(result)
We should fail fast when we can't find results by deviceName

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/client/src/main/kotlin/com/avito/runner/scheduler/runner/TestRunnerImpl.kt
> +                        expectedResultsCountByDeviceName.forEach { (deviceName, expectedCount) ->
We should extract all these counting stuf to some listener or something

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/service/src/main/kotlin/com/avito/runner/service/worker/device/Device.kt
> +        public data class ReservationNotNeeded(val deviceName: String) : Signal()
As I wrote before these two signals are not about Device.Signal

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/service/src/main/kotlin/com/avito/runner/reservation/DeviceReservationWatcherImpl.kt
> +        val deployments: MutableMap<String, String> = mutableMapOf()
Looks like we don't have to store this state there. We could store it directly in Claimer

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/device-provider/impl/src/main/kotlin/com/avito/android/runner/devices/internal/LocalDevicesProvider.kt
> +    override suspend fun releaseReservation(name: String) {
add //empty

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/device-provider/impl/src/main/kotlin/com/avito/android/runner/devices/internal/FakeDevicesProvider.kt
> +    override suspend fun releaseReservation(name: String) {
add //empty

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/device-provider/impl/src/main/kotlin/com/avito/android/runner/devices/internal/kubernetes/KubernetesReservationReleaser.kt
> +        deploymentName: String
This deployment should be removed from `deployments` that we iterate through in `release`

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/device-provider/impl/src/main/kotlin/com/avito/android/runner/devices/internal/kubernetes/KubernetesReservationReleaser.kt
> +        with(CoroutineScope(coroutineContext + CoroutineName("delete-deployment-$deploymentName"))) {
These code should be reused

2022-02-08 13:16 UTC, sboishtyan commented on subprojects/test-runner/device-provider/impl/src/main/kotlin/com/avito/android/runner/devices/internal/kubernetes/KubernetesReservationReleaser.kt
> +                kubernetesApi.deleteDeployment(deploymentName)
In current behaviour is problem. When we create a deployment we call `deploymentPodsListener.start`. This start coroutine that poll deployment for new pods. This couroutine should be stopped gracefully after deployment delition

2022-07-07 13:06 UTC, dsvoronin commented
Thanks for the contribution, but we decided to halt development of the test-runner in favor of "EmCee for android"
This PR will not be merged.

You can fork it if you want

2022-07-07 13:06 UTC, closed without merging