Allow local run in k8s by port forwarding
avito-tech/avito-android pull request #1324
Opened 2022-02-01 19:32 UTC by materkey

Expected:
When I want to debug runner I run it locally
Actual:
K8s network isolation does not allow me to access devices

2022-02-06 15:22 UTC, sboishtyan commented
Could you describe why LoocalDeviceProvider doesn't fit your goals?

2022-02-06 15:32 UTC, sboishtyan requested changes

2022-02-06 15:32 UTC, sboishtyan commented on subprojects/test-runner/client/src/main/kotlin/com/avito/runner/config/RunnerInputParams.kt
> +    val needForward: Boolean,
Intention is not clear

2022-02-06 15:32 UTC, sboishtyan commented on subprojects/test-runner/device-provider/impl/src/main/kotlin/com/avito/android/runner/devices/internal/kubernetes/RemoteDeviceProvider.kt
> +            val name = portForward?.let { portForward ->
I'm defenetly think that If this change would be done it should be done with new layer of absctraction. For example `DevicePortProvider`

2022-02-06 15:32 UTC, sboishtyan commented on subprojects/test-runner/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsTask.kt
> +            needForward = project.getOptionalStringProperty(
You should add this to gradle Extention. And choose better name. `adbDevicePortForward` for example

2022-02-06 15:32 UTC, sboishtyan commented on subprojects/test-runner/kubernetes/src/main/kotlin/com/avito/k8s/model/KubePod.kt
> +public class KubePod(private val pod: Pod, public val portForward: LocalPortForward? = null) {
should be resolved with inheritence. I don't like optional fields they smell

2022-02-06 15:32 UTC, sboishtyan commented on subprojects/test-runner/kubernetes/src/main/kotlin/com/avito/k8s/KubernetesApiImpl.kt
> +    override val needForward: Boolean,
We should change bool to sealed class PodPortForwardConfig { disabled, Enabled(port = 5555)

2022-07-07 13:06 UTC, dsvoronin commented
Thanks for the contribution, but we decided to halt development of the test-runner in favor of "EmCee for android"
This PR will not be merged.

You can fork it if you want

2022-07-07 13:06 UTC, closed without merging