Ci plugin & dependencies lint [MERGE_WHEN_READY]
avito-tech/avito-android pull request #56
Opened 2020-01-20 17:52 UTC by dsvoronin

2020-01-20 19:23 UTC, eugene-krivobokov requested changes

2020-01-20 19:23 UTC, eugene-krivobokov commented on dependencies-lint/README.md
> +Lint для поиска излишних зависимостей.
Добавь пожалуйста https://github.com/nebula-plugins/gradle-lint-plugin#license
Оттуда некоторые классы взял

2020-01-20 21:12 UTC, dsvoronin commented on dependencies-lint/README.md
> +Lint для поиска излишних зависимостей.
никогда не делал, не знаю как, сможешь запушить в ветку?

2020-01-21 07:33 UTC, eugene-krivobokov commented on dependencies-lint/README.md
> +Lint для поиска излишних зависимостей.
хорошо, добавлю

2020-01-21 07:34 UTC, eugene-krivobokov commented on dependencies-lint/README.md
> +Lint для поиска излишних зависимостей.
https://softwareengineering.stackexchange.com/questions/220068/file-with-apache-2-0-and-my-modifications

2020-01-21 08:05 UTC, eugene-krivobokov approved these changes

2020-01-21 08:08 UTC, dsvoronin commented on dependencies-lint/README.md
> +Lint для поиска излишних зависимостей.
спасибо!

2020-01-21 08:17 UTC, merged